### PR TITLE
Adjust <Compile> for PTB

### PR DESCRIPTION
**Pull request by envygeeks**
Fix an issue where most of Azu is included when building the API leading to errors when plugins like QuickStackSort rely only on the API to create a compatibility layer

### CODE REVIEW

**Comment by AzumattDev** [comment]
Hey there, I appreciate it. Though i have already fixed this mod for the PTB and have plenty of more things down the pipe. Seeing as this PR only adds a `}` I will safely reject this. Thank you for the time.

Please never play modded on the PTB

**Comment by envygeeks** [comment]
My main interest was in the API and its compatibility with other mods using it, like Quick Sort Stack. I'm not sure how adding this would detract from your larger plans. This change simply ensures that your project compiles on both PTB and the current release. Right now, it doesn't compile properly, or if it does, it includes unnecessary code that leads to its own set of issues and errors.

**Comment by envygeeks** [comment]
I mean I seen what I seen in the debug logs when I compiled your source and it failed to work 🤷‍♂️ . if we want to dismiss that, that's on you not on me. I got your source cleaned up and working on my Valheim w/ PTB on MacOS and all the extra code removed, and the other addon to work with PTB too. IDK what a single line change has to do with quality but I can send the entire rewrite of your addon if you want. I was just trying to be nice and send a single relevant change rather than sending the entire rewrite so it's not so slow.

**Comment by AzumattDev** [comment]
Considering it sounds like you re-wrote things, I can only assume that the issues came from your rewrite. I understand you trying to be nice, but I do not have issues in my mods when using the API.

One line changes are better just communicated via some form of text/voice based communication. The reason is that even small changes take time to review, and in many cases, they don’t add enough impact to justify the process. I want to encourage more substantial contributions that align with the project's goals and help move it forward. Considering I never have issues with the API and decompiling the 1.0.1 dll doesn't show any additional code besides the API methods, I would suggest that it's something you have done. To add more to it, BowsBeforeHoes, MagicPlugin, Backpacks and various other mods use the API successfully without issues for months now.

This is not to put down the contribution, but to simply state that if you modify the source code (rewrite that you speak of) and are having issues compiling, it's likely your changes that caused it overall. I appreciate the willingness to help, but the contribution is minimal compared to the effort needed to respond, review, and simply keep up with this conversation.

Screenshot of decompiled 1.0.1 provided.

image

**Comment by AzumattDev** [comment]
Just wanted to note that I appreciate the help once more, but since there's no license on my project, it technically means no one is allowed to use, modify, or compile the code without my explicit permission. I get that you’re probably just trying to do something nice, but copyright law basically defaults to 'no touching' if there’s no license in place.

That said, I prefer to keep control over the code for now and prefer if you didn't attempt to play modded on the PTB with my mod in a modified state. This is mostly because if you encounter issues or redistribute the mod in any fashion, it backlashes to me.

 If you're interested in collaborating or contributing down the line, we can definitely talk about it, but more ideally with my permission.

Thanks for understanding

**Pull request closed without merging**
